name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: docker build -f infra/docker/Dockerfile.backend -t jibangyoung/backend-prod:latest .

      - name: Build Frontend Docker Image
        run: docker build -f infra/docker/Dockerfile.frontend -t jibangyoung/frontend-prod:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image to Docker Hub
        run: docker push jibangyoung/backend-prod:latest

      - name: Push Frontend Image to Docker Hub
        run: docker push jibangyoung/frontend-prod:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull jibangyoung/backend-prod:latest
            docker pull jibangyoung/frontend-prod:latest

            docker stop jibangyoung-backend || true
            docker rm jibangyoung-backend || true
            docker run -d --name jibangyoung-backend -p 8080:8080 jibangyoung/backend-prod:latest

            docker stop jibangyoung-frontend || true
            docker rm jibangyoung-frontend || true
            docker run -d --name jibangyoung-frontend -p 3000:3000 jibangyoung/frontend-prod:latest
